---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ipcollector-sa
  labels:
    app.kubernetes.io/name: k8s_egress_networkpolicy_manager
    app.kubernetes.io/instance: k8s_egress_networkpolicy_manager-ipcollector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ipcollector
  labels:
    app.kubernetes.io/name: k8s_egress_networkpolicy_manager
    app.kubernetes.io/instance: k8s_egress_networkpolicy_manager-ipcollector
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get","list", "create", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ipcollector
  labels:
    app.kubernetes.io/name: k8s_egress_networkpolicy_manager
    app.kubernetes.io/instance: k8s_egress_networkpolicy_manager-ipcollector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ipcollector
subjects:
  - kind: ServiceAccount
    name: ipcollector-sa
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ipcollector
  namespace: default
  labels:
    app.kubernetes.io/name: k8s_egress_networkpolicy_manager
    app.kubernetes.io/instance: k8s_egress_networkpolicy_manager-ipcollector
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get","list", "create", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get","list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ipcollector
  namespace: default
  labels:
    app.kubernetes.io/name: k8s_egress_networkpolicy_manager
    app.kubernetes.io/instance: k8s_egress_networkpolicy_manager-ipcollector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ipcollector
subjects:
  - kind: ServiceAccount
    name: ipcollector-sa
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipcollector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s_egress_networkpolicy_manager
      app.kubernetes.io/instance: k8s_egress_networkpolicy_manager-ipcollector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8s_egress_networkpolicy_manager
        app.kubernetes.io/instance: k8s_egress_networkpolicy_manager-ipcollector
    spec:
      serviceAccountName: ipcollector-sa
      automountServiceAccountToken: true
      containers:
      - name: ipcollector
        image: ipcollector:latest
        imagePullPolicy: Never
        volumeMounts:
        - name: admin
          mountPath: "/var/run/secret/users"
          readOnly: true
      volumes:
      - name: admin
        secret:
          secretName: ip-curator-users
          items:
          - key: admin
            path: admin
      restartPolicy: Always